node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry4e349a7%26nonce%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI0M2YxN2M1Zi05YmE0LTRmMTMtODUzZC05ZDAwNzRlMzQ5YTciLCJleHAiOiIyMDIyLTAzLTI5VDA5OjAyOjA1LjMyODQ1ODI3NFoiLCJpYXQiOiIyMDIyLTAzLTI5VDA4OjU3OjA1LjMyODQ1OTI4MVoiLCJyZnAiOiJrdVVpRGw0TktuMTRTeXNmUG1UekZnPT0iLCJ0YXJnZXRfbGlua191cmkiOiJodHRwczovL2h1Yi5kb2NrZXIuY29tIn0.vCZ2ZxoMQ6Z9jSkSRuN-ArDlytLQJ7ADI01opcKQ5DI%26redirect_uri%3Dhttps%253A%252F%252Fhub.docker.com%252Fsso%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%26state%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI0M2YxN2M1Zi05YmE0LTRmMTMtODUzZC05ZDAwNzRlMzQ5YTciLCJleHAiOiIyMDIyLTAzLTI5VDA5OjAyOjA1LjMyODQ1ODI3NFoiLCJpYXQiOiIyMDIyLTAzLTI5VDA4OjU3OjA1LjMyODQ1OTI4MVoiLCJyZnAiOiJrdVVpRGw0TktuMTRTeXNmUG1UekZnPT0iLCJ0YXJnZXRfbGlua191cmkiOiJodHRwczovL2h1Yi5kb2NrZXIuY29tIn0.vCZ2ZxoMQ6Z9jSkSRuN-ArDlytLQJ7ADI01opcKQ5DI', 'd10d73e5-8838-49bd-b4cc-7715824b397e') {
       def app = docker.build("https://github.com/examplePy/docker-demo:${commit_id}", '.').push()
     }
   }
}
